language: node_js
node_js:
  - "stable"
install:
  - npm install
script:
  - npm test
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: "examples/dist"
  on:
    branch: master
